name: patient_care
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  firebase_analytics: ^9.0.4
  sqflite: ^2.0.1
  path_provider: ^2.0.8
  path: ^1.8.0
  # share_plus: ^3.0.4
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.9.2
  intl: ^0.17.0
  share_plus: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  generate: true
  uses-material-design: true